name: User Story
description: Describe a feature from the user's perspective
title: "[Story] "
labels:
  - story
  - virtual-team
assignees: []  # or: ["your-username"]
body:
  - type: input
    id: persona
    attributes:
      label: As a
      placeholder: user/persona
    validations:
      required: true

  - type: input
    id: capability
    attributes:
      label: I want
      placeholder: capability
    validations:
      required: true

  - type: input
    id: benefit
    attributes:
      label: So that
      placeholder: benefit
    validations:
      required: true

  - type: textarea
    id: ac
    attributes:
      label: Acceptance Criteria (Gherkin)
      description: Use GIVEN / WHEN / THEN lines
      placeholder: |
        - GIVEN ...
          WHEN ...
          THEN ...
    validations:
      required: true

  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies
      placeholder: "- …"

  - type: textarea
    id: notes
    attributes:
      label: Notes
